_BASE_: "./Base-RCNN-FPN-Cityscapes_robust_start.yaml"
MODEL:
  WEIGHTS: "./models/regionclip_finetuned-coco_rn50_fpn.pth"
  BACKBONE:
    NAME: "build_clip_resnet_fpn_backbone"
  PIXEL_STD: [57.375, 57.12, 58.395]
SOLVER:
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  CLIP_GRADIENTS:
    CLIP_TYPE: "norm"
    ENABLED: True
OUTPUT_DIR: "output/cityscapes/robust_start/regionclip_fpn/"

