_BASE_: "./Base-RCNN-FPN-Cityscapes_robust_start.yaml"
MODEL:
  WEIGHTS: "output/cityscapes/robust_start/imagenet_fpn/cityscapes_foggy_val_model_best.pth"
EMA:
  ENABLED: True
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    STANDARD_ROIH_CLS_ENABLED: False
    STANDARD_ROIH_REG_ENABLED: False
    STANDARD_OBJ_ENABLED: False
    STANDARD_RPN_REG_ENABLED: False
    DISTRIBUTION_ROIH_CLS_ENABLED: True
    DISTRIBUTION_OBJ_ENABLED: True
    DISTRIBUTION_ROIH_REG_ENABLED: True
    DISTRIBUTION_RPN_REG_ENABLED: True
    FEATURE_DISTILL_ENABLED: True
    FEATURE_DISTILL_WEIGHT: 0.05
    FEATURE_DISTILL_METHOD: "attn"
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
SOLVER:
  STEPS: (30000,)
  MAX_ITER: 40000
  BASE_LR: 0.02
  GAMMA: 0.5
  CHECKPOINT_PERIOD: 1000
  BACKWARD_AT_END: False
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/cityscapes/dcr/imagenet_fpn/"
