_BASE_: "./DCR-Cityscapes-to-FoggyCityscapes.yaml"
MODEL:
  WEIGHTS: "output/cityscapes/robust_start/regionclip_fpn/cityscapes_foggy_val_model_best.pth"
  BACKBONE:
    NAME: "build_clip_resnet_fpn_backbone"
  PIXEL_STD: [57.375, 57.12, 58.395]
SOLVER:
  CLIP_GRADIENTS:
    CLIP_TYPE: "norm"
    ENABLED: True
OUTPUT_DIR: "output/cityscapes/dcr/regionclip_fpn/"
